### ISSUE TITLE
compare to clusterProfiler

### ISSUE THREAD

**Issue by slowkow** [JEFworks/liger#1]
The Bioconductor package [clusterProfiler](http://bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html) does several tests, including one that is similar to GSEA.

**Comment by assaron** [comment]
Agree with @slowkow More exactly, comparison with [fgsea](http://bioconductor.org/packages/release/bioc/html/fgsea.html) (currently, the default back-end for cluterProfiler's GSEA) is required.

**Comment by JEFworks** [comment]
Thanks for the suggestions! I agree a comparison with `fgsea` is warranted. This issue has been addressed in commit 6a836a5bcb5c1df3859245bc2c7f314cc5238455 .

**Comment by assaron** [comment]
Thank you! Now I'm wondering, is the statistic you use different from Broad's GSEA? Could you clarify this somewhere in vignette too? I got the impression that it's the same, as you reference Subramanian et al, but then the results shouldn't be different from fgsea.
