### ISSUE TITLE
Tutorial Webpages Missing

### ISSUE THREAD

**Issue by samuel-marsh** [JEFworks/liger#4]
Hi Dr. Fan,

It appears that the webpages for the tutorials in the ReadME no longer work (or point towards current addresses).  Hoping this can be restored?

Thanks!
Sam

**Comment by JEFworks** [comment]
Thanks Sam! Fixed in d6dc93799bec5dee42f868f185ff07f8939044f9

**Comment by samuel-marsh** [comment]
Awesome, thanks so much!!
